POST http://localhost:3009/api/auth/register
Content-Type: application/json

{
    "username":"Jyothi Shinde",
    "password":"jshinde@2020"
}

###

POST http://localhost:3009/api/auth/login
Content-Type: application/json 

{
    "username":"rahul attuluri",
    "password":"rahul@2021"
}

###
GET http://localhost:3009/profile 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsIGF0dHVsdXJpIiwiaWF0IjoxNzMzNzIyNzA0fQ.tU4LdYRrxPrR4_Q2Iu3KABD_geN3ebpQwc4cmfIQXTU


###
POST http://localhost:3009/api/tasks
Content-Type: application/json 

{
    "user_id":3,
    "title":"Reading News Paper",
    "description":"Daily updates ",
    "status":"In Progress"
}

###
GET http://localhost:3009/api/tasks/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsIGF0dHVsdXJpIiwiaWF0IjoxNzMzNzIyNzA0fQ.tU4LdYRrxPrR4_Q2Iu3KABD_geN3ebpQwc4cmfIQXTU


###
GET http://localhost:3009/api/tasks/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsIGF0dHVsdXJpIiwiaWF0IjoxNzMzNzIyNzA0fQ.tU4LdYRrxPrR4_Q2Iu3KABD_geN3ebpQwc4cmfIQXTU


###
PUT http://localhost:3009/api/tasks/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsIGF0dHVsdXJpIiwiaWF0IjoxNzMzNzIyNzA0fQ.tU4LdYRrxPrR4_Q2Iu3KABD_geN3ebpQwc4cmfIQXTU
Content-Type: application/json

{
    "user_id":1,
    "title":"Learn HTML",
    "description":"Exited to learn new languages",
    "status":"completed"
}

###

DELETE http://localhost:3009/api/tasks/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsIGF0dHVsdXJpIiwiaWF0IjoxNzMzNzIyNzA0fQ.tU4LdYRrxPrR4_Q2Iu3KABD_geN3ebpQwc4cmfIQXTU

